id: IB2682C2D
legacy_id: P004235
ocr_import_info:
  bdrc_scan_id: W23556
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T17:59:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:13:06.311806+00:00'
last_modified: 2022-09-02 09:15:34.461300
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23556
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23556
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། སངས་རྒྱས་རྡོ་རྗེ།
  author: མཁས་དབང་སངས་རྒྱས་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.8255658484846127
  ocr_word_median_confidence_index: 0.8999999761581421
quality: null
bases:
  I2132:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2132
      total_pages: 702
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2132.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8207876373770059
    legacy_id: v001
  I2136:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2136
      total_pages: 632
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2136.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8315167745188604
    legacy_id: v005
  I2137:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2137
      total_pages: 630
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2137.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8269926670348894
    legacy_id: v006
  I2139:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2139
      total_pages: 636
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I2139.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.8131871806876974
    legacy_id: v008
  I2134:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2134
      total_pages: 640
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2134.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.8109550343513642
    legacy_id: v003
  I2133:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2133
      total_pages: 616
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2133.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.8208447536109085
    legacy_id: v002
  I2135:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2135
      total_pages: 644
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2135.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8349163103228809
    legacy_id: v004
  I2138:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2138
      total_pages: 650
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I2138.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.8456038049416347
    legacy_id: v007
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
