id: IB2682C2D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T18:01:16+00:00'
last_modified: '2022-06-07T21:17:43.392682+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23556
  title: གསུང་འབུམ། སངས་རྒྱས་རྡོ་རྗེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    5B98:
      image_group_id: I2132
      title: ''
      total_pages: 702
      order: 1
      base_file: 5B98.txt
    A51D:
      image_group_id: I2133
      title: ''
      total_pages: 616
      order: 2
      base_file: A51D.txt
    B480:
      image_group_id: I2134
      title: ''
      total_pages: 640
      order: 3
      base_file: B480.txt
    144E:
      image_group_id: I2135
      title: ''
      total_pages: 644
      order: 4
      base_file: 144E.txt
    6B48:
      image_group_id: I2136
      title: ''
      total_pages: 632
      order: 5
      base_file: 6B48.txt
    5C46:
      image_group_id: I2137
      title: ''
      total_pages: 630
      order: 6
      base_file: 5C46.txt
    DDAF:
      image_group_id: I2138
      title: ''
      total_pages: 650
      order: 7
      base_file: DDAF.txt
    48E8:
      image_group_id: I2139
      title: ''
      total_pages: 636
      order: 8
      base_file: 48E8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
